# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangtarget_platformosx-64
    - CONFIG=osx_c_compilertoolchain_ctarget_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ORhxNV8KLSKwniu/fliLUtdhtYr4l7Ze3APioYVKd0Ts6H2Ijc1Rp3/q0cPA9/tNflDJBAQVB5bM5G6+dyquHxbs3XLASwlYBMDGqX4xMfoisAvynibVYlCi9DE3Iqey/6IaeKuPanzc4QiLXahM9cz2/2BTeDvrc7LyMsbVS8CM5PaGzzM1NmVaMsfx4oq8EN7WMPsR6FukpVLzckrBfz6yqWvw+rn/0HBqC8cTI6dwXC2328v6Pc0dWMPfBKW0j5iGaVkYHec2Go7Xn/cfcqYQIpdEHXJQRhq6Bq9t7MQnQxOmGVd96k1LPym7QKO3g+BrbDwHv+92xsf2PLG0LqyRbOY1FTk7k0gtb/+nYx8tS01JULro2fdnE84QkRMmR+qutS/YWdY1H8FSe+JfBUmIjcKtebMVx5UQ+wAHWlmWrExDVJV4WmX1u3nfeyVXOjiOedkaf+WpUPeHur3zd6MH05yqyeU6Lj+GGIuc2MDk/t/z4Mj6cB01FmpLQx9WMPPqxFE9OX79SOxlovE/ycL12Lhc9vjY6s7BrGx658jdUNdJlo9Nt3WuFRdnRe04p79s0dQuf1J3l9i92m2zT81bQko6ubuglOshflXaFUkepfHjC50UJi/coWxocLw6a8xG6SfDaEQYEGgAMDEm60W75JJI+BkG+wQubpGUu84="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
