# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ZZd3X/hz6eKk2CCoD2rfdx/LogMaaC5qSCerydMwQLJEftvWTQ8YWMm21I2PY05BYeVBKYInXSja9qkTunCy8c5oUl2hxrgk8w0PN7g8+bPNNeJcayxNfQHISrXKOmmGGRd+zY6SEUT87rRKExm/Ve1MSpueTcXlxj+dHTCxmsFQu8QWxrRZ0MKjiaCqr6oTawyx6PwthmzRuIeZ9Rw8wUbBNEdM6/jxn43/uPu3f3EcMVHJiWuKmG/p2aQMKGOcErxGtSZle2gy5Z2A8LxkoU5LJ75WrnuJp1JvJgg/vKNC+/xtEHBgVWf4Es/FGHHoQcQGA4LLvjTQDgS4YKaBKVnXiFvQUNcDMdo48HUg2MWW2XijV/NPLmpDjFdARxPW8jb8EE4LEcnJECEiPU7ciEYs1bqqBCc1QWaFNG36oJ5FrLe4seybaKe+HbTf3C3dHxiWtCdqmvFrRKad9wmPbbbjXEPAaV1RUJZkjEmfvbLbd5eaZ2TIz6Eg7OoCawW14fzbh5UUXBGjohRVJMRk3/FJT9KIxbCt7ZYNNM4TPVTXEqGx5mweQq1Mbny0/N5KcXi9A2XNsqmsJBWBZQuM4OArWAHswHGXIEFRgOn/CID5J6FqLo4+7iZ09mfFBKWEc/dEYhjFLQO+Z+mSo8dc6ANzW1Xw/I4hfsbOcU18QQY="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
