travis:
  secure:
    BINSTAR_TOKEN: ZZd3X/hz6eKk2CCoD2rfdx/LogMaaC5qSCerydMwQLJEftvWTQ8YWMm21I2PY05BYeVBKYInXSja9qkTunCy8c5oUl2hxrgk8w0PN7g8+bPNNeJcayxNfQHISrXKOmmGGRd+zY6SEUT87rRKExm/Ve1MSpueTcXlxj+dHTCxmsFQu8QWxrRZ0MKjiaCqr6oTawyx6PwthmzRuIeZ9Rw8wUbBNEdM6/jxn43/uPu3f3EcMVHJiWuKmG/p2aQMKGOcErxGtSZle2gy5Z2A8LxkoU5LJ75WrnuJp1JvJgg/vKNC+/xtEHBgVWf4Es/FGHHoQcQGA4LLvjTQDgS4YKaBKVnXiFvQUNcDMdo48HUg2MWW2XijV/NPLmpDjFdARxPW8jb8EE4LEcnJECEiPU7ciEYs1bqqBCc1QWaFNG36oJ5FrLe4seybaKe+HbTf3C3dHxiWtCdqmvFrRKad9wmPbbbjXEPAaV1RUJZkjEmfvbLbd5eaZ2TIz6Eg7OoCawW14fzbh5UUXBGjohRVJMRk3/FJT9KIxbCt7ZYNNM4TPVTXEqGx5mweQq1Mbny0/N5KcXi9A2XNsqmsJBWBZQuM4OArWAHswHGXIEFRgOn/CID5J6FqLo4+7iZ09mfFBKWEc/dEYhjFLQO+Z+mSo8dc6ANzW1Xw/I4hfsbOcU18QQY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
