travis:
  secure:
    BINSTAR_TOKEN: Eya+Je5Nx+5D06Oqt6knoCoiBLMra8Ow3PPti7hClY/h8rXX/p7UYym82Jk41eOZlH2PIEC1g5ukeIOLECqt6R61URRNWFmiPf7Hj87DswFAkqfLCSAqlPhwtlAcqqkMnWznJtSs9FUwBrfc0EMTe32cHnltSY4/uVoqgZnem5ovGpJ02dxdsp5EQwY0DXBWc89gTaofAWktojeFd6RbyDrFG8lYLRkTAvAh9/riD4OoQb+ptJl83yOMpUxurC3/fZ/CoLg5GyFhMU/F4gPDYTl8q4DmLddqi7xEAbeGttSPIeZ5jrsn02wJ4to5+r9yJBWkhZtvoqnicuJ1SXgE1WbsgrXBDo016ncpWB1VdIpmOaBObH58cOHFoZjBq9dF70Usuyt0H7p/DLvueQqt/gHYa9Qm/7vwb5jZ7LzCB5M4o6xUt9y9o6YV0XM1+2cG/UCTNwEfAhF2iCm8nWh9u0rm1y/iW4GOkty4LrrgcrPRbOGMlhyUIZlirYcKfdO/yfyokSdNk9HOgNrMDyRVFZlZSVf6XS37VHkKlFYJubP5jC8n+erxT6La0xby9qQISutp0h6WjWg+UurYQEvREA5Jqt/K0YisxLj4DVlPz+9k7C8nEQqrRQNpiuhkdhItPVVV8To4I3te+HOqpprSn0VG9fbp93MI6FgV6kXKlXE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
