travis:
  secure:
    BINSTAR_TOKEN: IhFgS5OeDTjRgZCVFrTRlS2A/jftsCkkaa3FLtYUdPigTCcEISFKhS28WFilU/x2vE+hx+G4GMcb6qN4pAt/ldgiVTxEBqRLMvv59R4/yj96gTVHIeQGWD4kfyNWyf4Y8+AcPsGH6EJIwaegrokWyUa/f+cf2w65Aj/ZpB2+geQNGoC8uzqMJlFmUQ/Ad1QiQPrvfo4iPTucXsWb0e9l+PlhmL0SyDwG2C2suVJcKmwSzoVTfA+TFhIV27jJayQXGOV+dnoOK4mbiTRVxG07SD1fWRsEsMV2MpW/T+w6qdAnDDyWpP0AJL0ByBHFFGFrML0B+fnaq69jGtcHY8Z8DNLKwUQo6h8PlZm9boSLuAwh/nl1+yJSkuFrffwAO+UG9xVKOO1anjiinxSzew/bi49d2j1ufINLmQlZkCN4jf7Rtj4QWxSaXX92w1Xg/oUtPsjoWdmbrwZBPIYQIvkpkZIoiXjAxgpYAtteHpR/UmAnfsO+o/UybHNgjVBtw3LntX7FN0b5j+MyENusavZr2WWdCUqjEWtpjqfxpFmxeeO3IxoAJBrL+J97qEjDjc/jVYQDZbJRcJfHlQhrw/zOUDCpW81q++AvWV05jQADK0U5tsLfaI+Wp7D+0DyrXYn56fYpQQCbDmveUgB2pnDDXVmqM2wTjqA9h1iAZlw3vpc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
