travis:
  secure:
    BINSTAR_TOKEN: Mg70yZ+PQX8ruXhc9AyXP19fm5jdr8s0eG5UcRNo665PW47IXqZHI5CYdYnQPUFdGx0MGcQzCP0ecHlNpceYWOnTlOh7Pf4vdtoIIwVqblxuPGgMrEEwOMjLxhpMamrohbw0KnxKxBJkSvOpz3FCh2j79jQBO1ky9tK0oxKdQ85ZX12yB/PPtHA66u4f3Am9HIk8YYT51cZxYw99XAPH9UX/bDTO2Oc05SsWB37B1Uz2ZG1E/4XhXlltdzgowC2D97MPcAMs3jhb5M03PFLx1tBD7C3eJzd4mqPI6qL4QfN951r1XbnyjiqWvPtaevZPmHpSMHXKsB81MsQFv4gnQEkCQxV3S/mbE2L9Glf2p1ph8jRpT1lMk+NmnuxqcoBWAVMsUY8Gv8anisGvMJvNWkiE/MNSMmFBHOI7nnOpJ7m+SKLuC+N9cmsWFsTXb9DBhV7LJEdn1HXhsYR0gy609gclGnYk5HLJDnvoUeVG4C21YbicYMqkw89jPdE05pofJsLolWvpjL5B6wXbz11q0kHVwM3ixZ7RXAJEiB51GYWtST3an7UgwHFz+BSpyNYGqbB0lZrzsI1LN26+65TTpLkZetotD2TLIi8OyW7IjBdAtTX4JW2uN3dkPq2YQTgi+hg/+mBzyrIj2gHzrDwDwdw9uD5llvmwumnJ6N4a1f4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
