travis:
  secure:
    BINSTAR_TOKEN: KrRwa72T0cAMnBT99v+Sn+Kmgem6QNz26CQqdIz+S0Yj+HVbpsVA8vATb/TeuZOgb/Pg510fYHGeyIR3y1CH85uVGVZH+2RLipj/RkGl4QIcqMRnrOMTuTthmCAZ3tJZRBQrCvfKk4g1+nfK1DFWqn4UCFq8w4VGgH0aukxAeReATAcU0yaYtJiIDib7Jnne2dV3WwlwGyO/aDsDkoyqgFrO/Amxi0WzFNo20z5UhIhybo1341nDK2h94aKV8olYX2ExPOKx7NQqtEVM95zRKxmecCS3VlK/pW7HTNBrcSA3xgeihZYqi10UVQBle6UQAepyFLHERkic1DdoFEqTGQjLnCyldUoH6D1rLEyTstSdPiAAGuES54pB7NZ/x39oMfl7G+/FoxKkMhCWza11duHNb1XIs5JBq/KA2elGWLuWI6RAv5T96E9Md1g8ukUG0grLPf5Q0AvvdJjtY5y98/FtSolQt7f0A0QSVGVGzs0TRq6FOlyDFeGDbZEuzz7I/77mdbvHzkF2dNsx+VRarq5MblBHsdkVgFc0xanL56wftws8MV4Y3VJ7SBqUjSNm+PIVz8FrYfEjPShWtg1+9eOGGS+HJo9Y+EAoGtIm90DjTtNCqRjZsk8Xw1SUE4FofJjFHt1yuuyBoR3hwzB+sb1zvCkVj/PP9fQJy/BVgu0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
