travis:
  secure:
    BINSTAR_TOKEN: oDjUACIPSOOnzxqw6vR2RFWYmCv/4lCwm9ezmErT9dGEROaaIt+8rwJsPQbZ2z2Pii2/Vmi+ej0KWglhZVLpxsJOJuE6ER4A1/uPkjAyZ1vBqLHjYQv24h4joI7fypriB7yJbtQ3LmDSOGRjigrNNlTLUzGts6lkhoYkiLjTnduye9gobTjMkMkQraIbGWeDI8kUoEKxr/itGZPl0fySpl0KGtVI4twZZ0QJE937H/KUQ4hQ3bhTUXhLDhQCTrQq7hGWlqeg7oGUBE6YynYGkiPeQwH8QAuMDKYhpg/RtM6hXhbeKWJL1nV3UH19YXqt/DS5M6PIvBV6gy0Idqq7hgfOd+McBOPZVITyIT7GJVg8ravjipxj51LhmWYHojX2bcyaFM6jdobiWOX50i/dqF9jMR1ZofhP5XgoaP0JNGhD0Phbdoe9xN1O8UzfDQiR+GcCSKAUCp/epM3ZdCB+3gS3su37OV616baIdBph6F1STetSjaFOXcFKdZfMrgXLiGqh9JF21P6Qgsr/uziQgBW3+6AcsCf3vrDWKBkpTZek7/K+xpCuJJMkrOkTMvDj52HuJ7BeeSW5/bkGbc0Tv5JPJVl5OCpIF2M1TFOGdI48iUdTOEqguKnBx1+NUnVQ2ZtCNO3Pn1NCSNSLGeXBiZFLmU57cFIap+pmqs2UO0g=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
