travis:
  secure:
    BINSTAR_TOKEN: WYtd+hz+/Z2kYzpz3taotNTXtiG0oCnUtGnEZmQqtYuLIeU0T36knhks2kocxe5ymtvbp5KKakIlxttmUsgFSAtL+Loj5D4BqeSsiqksXV7ezMbaXi5CRR7maZWO9QtNJZcKPoQByH+gvDhnqtwcYg1KE/MwVOewXTdWaW9sJVG29sp1nd0yekgQHEJKPuadzkSwyrJ6i7mUFbtkFkwsi2ebElo2Xd20GMi07odDfaoRbvydrvxj8z9CrAxqYyZhwh+oZktm4v8MmvvPgwsIXrXDidgo9Ir6x+/zWjgVanjHnv58+awldXVlR5imCIfhc/qDdelCpqShj7HsaW3wa5MW4YMEllCln52k0dQFRb3u5S7pPurpOWoJkM7DeaNDqCu/RMkeRS6cUHlfhDKfS2nAhzYaKVB82PUd7fKxF6Et+8NnJGhCzsruNy+nuvEMM6pZQka+ytkxFQc/rP2Ej370Tj1kMbJsL/YVo24iNksaijh0J5n2eTaU7fugvq6KQaEZJn4sd3rB+h7aOhIQt9tbj8YGGeCfR97KN4LqHBWp1y2X/hw6E3NkCs0m2wRZ2YGEzwjdTabKhtI9BboOTwSU0S9Nheo4xgDkodHHD2yQmVebwx7RU3NMvcxBIw6L4cibGOcO97Phd3rv90IjSmGVEeXT1aZ0Myjx5nNplTI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
