travis:
  secure:
    BINSTAR_TOKEN: UVt3ap6dzN4Nuh6Jx4rXTBbJ2FAQw/emu68uUJD53ldY/MAgkeyucrvQgc4uvguBkRXnCDm4HdsfS6IdgDBy9PTv4t43zCCbhi/0frxv66HYuqIXu0cDzMQFyDfrflg+7HGIi7YsgrcFU/OA15Wb1aYpxXeZu2BWGidmCwerFfD9kVNa+6W1o8U5ky55K+UTh6ZavB9uRaRHe97wQh4YSUo6aEyLHWnIBSMTXyJGMz/Yu1JZv9r9I6NUY3zlrnTauAb5K7miYsD2/xYabhSQU9BWlwVa/YkW45l8qTihmm7/3EYZsBIhcgKJNc51WbVeNu68vg4W1E78G2BcClADIqAw9A8j0qCS8+xkVkurIQUTp+7zR1K3sbJwz8RwZ5cmliIZKeIglfs2ERVBd149OIw+YHUqRcsqm/BK94b6E1nK2IhFC1WEn8szdRGTRmqw291hJkvfyiiMEv05CfdF14McyL/MuLUh8AE2F3kdUmGfpTlFaNxSJWVp8z3PpC0AdxAZdfm8sJQVCAeqjcQfxflgefkxqemzd3QJrFKCSe4La/R5M5Ndg9zyDNcC/PZ/93D5VXhDjQcoe1wrv/f+Fp9EMSNJjq2jHfCasZgZcJ6/Lc56XSnCV+P8E2bQKpLFe9uLc7/GrxA9ItQfpsHTAK0u60c1+O8kvvsaLYT+EhU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
