travis:
  secure:
    BINSTAR_TOKEN: C7IHf+sGnr3kUxrhlmjPps7waAoAyIJRZy3H98WWL5OGvj8NyQi4wbrnr6RYHAlWK94igOIeU5o/dt9V7FgcF1gje2cNbrwf+38Xbr+Z+8QGQRDFJ0R8lk8OUKfFVMuWi6w8U7UDbQYeTniMOUF4QPlDAavXiNjeJjXPJbbInEwt9FhvtrBBjJ8soJCDniu9bKbf+MAq5Xh1nSgL0tKXCal5FJ9kRZXLn8WNk9/DUZDGqL39ywqnKZ2y9onNVjYXc1ZQlsG1S93LidzN1UADLd8GpUfrjd8eD6drEV/VVdr4i9VoaEmgqySiBuWAB8ZOaqt9Jm8myhA57i7FUcY6GiHqwwy1V1MgW+dw7ApJxxzhCfRTRKuRcslvbTg6Amx25CAFCWXMs665nI9wD4hyeNxOPZa5/UlB9jD+YAB+Mt0YOaCs+eTLIGieWimZ5PbXadafLUS3h794qJfapnu8up2O46LYQH6K2A3iQW5I+GMPpIfm0r1OvY979Tg5d1XQZzN0/fKmo36KLz5MlndozQmHqRpckG9DICgLvXS7YVB1d00OqotHwqKdGx+Mx5RShNmZfx5Kj5xXcpmanJBwwNcHdsKliKZyXjhGQE25JK/qlTuVUiXnwChmKsenHmwjm4sJKf+ceHGiWIV8Q3e4LI7VYOB8VehfgOK2FhZoIPM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
