travis:
  secure:
    BINSTAR_TOKEN: ORhxNV8KLSKwniu/fliLUtdhtYr4l7Ze3APioYVKd0Ts6H2Ijc1Rp3/q0cPA9/tNflDJBAQVB5bM5G6+dyquHxbs3XLASwlYBMDGqX4xMfoisAvynibVYlCi9DE3Iqey/6IaeKuPanzc4QiLXahM9cz2/2BTeDvrc7LyMsbVS8CM5PaGzzM1NmVaMsfx4oq8EN7WMPsR6FukpVLzckrBfz6yqWvw+rn/0HBqC8cTI6dwXC2328v6Pc0dWMPfBKW0j5iGaVkYHec2Go7Xn/cfcqYQIpdEHXJQRhq6Bq9t7MQnQxOmGVd96k1LPym7QKO3g+BrbDwHv+92xsf2PLG0LqyRbOY1FTk7k0gtb/+nYx8tS01JULro2fdnE84QkRMmR+qutS/YWdY1H8FSe+JfBUmIjcKtebMVx5UQ+wAHWlmWrExDVJV4WmX1u3nfeyVXOjiOedkaf+WpUPeHur3zd6MH05yqyeU6Lj+GGIuc2MDk/t/z4Mj6cB01FmpLQx9WMPPqxFE9OX79SOxlovE/ycL12Lhc9vjY6s7BrGx658jdUNdJlo9Nt3WuFRdnRe04p79s0dQuf1J3l9i92m2zT81bQko6ubuglOshflXaFUkepfHjC50UJi/coWxocLw6a8xG6SfDaEQYEGgAMDEm60W75JJI+BkG+wQubpGUu84=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
