travis:
  secure:
    BINSTAR_TOKEN: rHX6YOYBRH0enCRajY1gQAJ198cQEWR6gtVr585i4XdEQDCkOxGbVCVbdYCU34J59tEQGm8g3vVHUx72l0JOOEymdtMguuBj2DSNZO2aETkYTmUcZRoytUOQxgSAZcgr1QfA+ZpfiiXohTiE/4hWCJTvXcL8pEMw0AXI6L4lVNSKjGPJByHlgHC0huJjS1U5+0t7YEbhCnMh86Wkc8FqFv3X+2fCAdj071SUgp08ECfS2pK+ZzfmowvUgsmKtZkWsFKLkGJDw911RB70pb8FQqe5MKW7xDskoLW2aZNNgR9OSb7xxjq8sAR7swGkORHok1iDbXAB5QiAX1NH5yrXl9ucgkAxcjkmNQpHM0Gk619zImylcBC9oIufTWR9xbxLaVe+JuhNmowmOuHBrZ00pLlLGexf4D0gW38S0of7+aih3fbSyKdESEyYdk3Nxqtdn2gdiNK/9sTQ8zdG3TVdIS1XDcmmuJFNRfl/an95nPsBDoWZe8rGK7AbvUSo/Yk8RtdyAAgLRVGAeZ4dbsJKF/RA/TarsTS6/PfWms3qrUNeOulTmR1I4MgX1ua21APk28mJ7gKK5wUvHYAZDe00OLIGtXm3Kx+IFCDgMWSVBUUvN+lsyh4sIXcOTREaxSXrs9ZXPwufPweT5UJmM0M7M4eEk7ocss1uzrP4X14fOXo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
