travis:
  secure:
    BINSTAR_TOKEN: D0fLdQCTsL7AjkJRmxxnr3ad/cHD4896CgmZxXkvwLGB2Y2Ik6i9i5AslCf6t4VjLjxlcyqmgTYRYny104wQbs6vnLDoIWnbEqzcnOOstRHAsWd6E/B9quLtdGSK6Kak8luvt7MACw469FAxvhIAlKXwQyliMm2M38F1OuOq8kNbz7C0WO+7fMykBiDcByoDu3c/e04IFJ1P6z8ZyfZKmkzSZAYay2UwlbU3bGr8LTe+O3PohRZNk+KqSN2TEmXp4yeDDdI4WIOLUApRHSBEZWw8rCwceLY6QguFLpk0asTLoo+oRFeImrRuY1t+ep4uFuf6feNm+dnJ8rkIAcIrZY/bty1T6KkeiISPvlCsCAm+m0DgtTH5gZhtv5TDpy2/jUFsTxDQy8ZsElV3w9mXPY4s57oEUoxZYNpEt0sWLKUxK1tPKmThdIrFIumB0tAv+Ci0IExdITmJeFKB4M2/P1V8JQ8CQXgh0/g3g2QE+7fyiwwQDUbLHuF/432txT4DTkTgF6HKUIGr9IXdoLb3wktaRgtk8ItWKzj7+Ef9gNmntjo0lCHj+Enswt6VM5Cd3npBtPt1eWixzRrw74PVhF6CDsvn9jTl5DuA/vl4Kj0d84Tbo9VUDRtwEX1qACvNaT0GizEG+qufazwDh94SZ/QVnPZJL4LWK5nIhjZ41O0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
